### PR TITLE
Add addMoreItems(int, List<T>) to the PagingBaseAdapter

### PR DESCRIPTION
**Pull request by iamyorchdev**
Hi @nicolasjafelle, I'm using this library project within the SwipeRefreshLayout. So, to add new items to top of the ListView it is necessary to add the method PagingBaseAdapter.addMoreItems(int, List<T>)

This is my implementation: https://gist.github.com/lalongooo/95fbda3ebeaeff865438

### CODE REVIEW

**Comment by nicolasjafelle** [comment]
Hi ! Sorry to ask this but you are saying that your PagingListView has also the hability to refresh content and take new values (latest by date) and add them at the top of the list? So the steps are:
1. Swype from Top to Bottom to reveal the SwipeRefreshLayout
2. Connect to a Rest API and get new values
3. Add new values to the top of the PagingListView

is this correct?

**Comment by lalongooo** [comment]
Yes, that's correct :+1:

**Comment by nicolasjafelle** [comment]
Thanks!!

**Comment by lalongooo** [comment]
Thanks to you for accepting my pull-request... :)

**Comment by lalongooo** [comment]
@nicolasjafelle Just a quick question...when will this update will be available through maven central?

**Comment by nicolasjafelle** [comment]
Already in Maven central with version 1.3

**Pull request merged**
